spring.application.name=patient-service

# UNCOMMENT TO USE IN_MEMORY DATABASE

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin_viewer
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

server.port=4000

logging.level.root=info

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

spring.config.import=aws-secretsmanager:prod/patient-service/db
spring.datasource.url=jdbc:postgresql://${RDS_ENDPOINT}:5432/db
spring.datasource.username=${prod/patient-service/db.username}
spring.datasource.password=${prod/patient-service/db.password}
spring.cloud.aws.region.static=ap-south-1

spring.kafka.bootstrap-servers=${MSK_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=AWS_MSK_IAM
spring.kafka.properties.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
spring.kafka.properties.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never